plugins {
    id 'java'
    id "io.freefair.lombok" version "9.5.0"
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation("io.projectreactor:reactor-core:3.8.6")

    // log - logback
    implementation("ch.qos.logback:logback-classic:1.5.18")

    // reactor-debug-agent
    implementation("io.projectreactor:reactor-tools:3.8.6")
    implementation("org.postgresql:postgresql:42.7.13")
    implementation ("com.zaxxer:HikariCP:7.1.0")
    // testing
    testImplementation("io.projectreactor:reactor-test:3.8.6")
    testImplementation("org.junit.jupiter:junit-jupiter:5.13.4")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation("org.mockito:mockito-core:5.18.0")
    testImplementation("org.mockito:mockito-junit-jupiter:5.18.0")
}

test {
    useJUnitPlatform()
    // stub test classes without @Test methods yet
    failOnNoDiscoveredTests = false
}